# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2026 Mike Mol
"""Witnesses for `typedargs`: a parser's own `add_argument` calls type its namespace, or refuse."""

from __future__ import annotations

import libcst as cst

from mikemol.pycodemod import typedargs

HEADER = "from __future__ import annotations\n\nimport argparse\nfrom pathlib import Path\n"
PARSER = "    parser = argparse.ArgumentParser()\n"
TWO = 2

SOURCE = """\
from __future__ import annotations

import argparse
from pathlib import Path
from typing import cast


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", type=Path, help="where")
    parser.add_argument("--count", type=int, default=3)
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("names", nargs="*")
    args = parser.parse_args(argv)
    out = cast("Path | None", args.out)
    return len(args.names) + args.count + int(args.dry_run) + int(out is None)
"""

TYPED = """\
from __future__ import annotations

import argparse
from pathlib import Path


class MainArgs(argparse.Namespace):
    \"\"\"The typed result of `main` (generated by pycodemod typed-args).\"\"\"

    out: Path | None
    count: int
    dry_run: bool
    names: list[str]


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", type=Path, help="where")
    parser.add_argument("--count", type=int, default=3)
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("names", nargs="*")
    args = parser.parse_args(argv, namespace=MainArgs())
    out = args.out
    return len(args.names) + args.count + int(args.dry_run) + int(out is None)
"""


def _function(body: str) -> str:
    # A module whose `main` holds the given statements after a bare parser.
    indented = "".join(f"    {line}\n" for line in body.splitlines())
    return f"{HEADER}\n\ndef main(argv=None):\n{PARSER}{indented}"


def _field(expression: str) -> typedargs.Field | str:
    call = cst.parse_expression(expression)
    assert isinstance(call, cst.Call)
    return typedargs.field_of(call)


def test_a_parser_in_one_function_gets_a_typed_namespace() -> None:
    """⚑ Class above the function, `namespace=` on parse_args, the cast and its import gone."""
    got = typedargs.plan(SOURCE)
    assert got.text == TYPED
    assert got.parsers == 1
    assert got.refusals == []


def test_parse_args_with_no_arguments_gets_the_keyword_alone() -> None:
    """⚑ `parse_args()` becomes `parse_args(namespace=...)`, with no stray comma."""
    got = typedargs.plan(_function('parser.add_argument("--x")\nargs = parser.parse_args()'))
    assert "args = parser.parse_args(namespace=MainArgs())" in got.text


def test_each_add_argument_shape_declares_its_type() -> None:
    """⚑ Optional unless required, defaulted or positional; a list for many; bool for a flag."""
    cases = {
        'parser.add_argument("--mode")': "str | None",
        'parser.add_argument("--root", default="/")': "str",
        'parser.add_argument("--x", type=int, default=None)': "int | None",
        'parser.add_argument("src")': "str",
        'parser.add_argument("--need", required=True)': "str",
        'parser.add_argument("--item", action="append")': "list[str] | None",
        'parser.add_argument("--many", nargs="+", type=int)': "list[int] | None",
        'parser.add_argument("--level", action="count")': "int | None",
        'parser.add_argument("--level", action="count", default=0)': "int",
        'parser.add_argument("--q", nargs="?")': "str | None",
        'parser.add_argument("path", nargs="?")': "str | None",
        'parser.add_argument("--flag", action="store_false")': "bool",
        'parser.add_argument("--p", type=pathlib.Path)': "pathlib.Path | None",
    }
    for expression, want in cases.items():
        got = _field(expression)
        assert isinstance(got, typedargs.Field), (expression, got)
        assert got.annotation == want, (expression, got.annotation, want)


def test_the_destination_follows_argparse_naming() -> None:
    """⚑ First long option, dashes to underscores; a short-only flag; an explicit dest wins."""
    cases = {
        'parser.add_argument("-v", "--dry-run", action="store_true")': "dry_run",
        'parser.add_argument("-v", action="store_true")': "v",
        'parser.add_argument("--x", dest="y")': "y",
        'parser.add_argument("name")': "name",
    }
    for expression, want in cases.items():
        got = _field(expression)
        assert isinstance(got, typedargs.Field), (expression, got)
        assert got.dest == want, (expression, got.dest, want)


def test_what_cannot_be_derived_is_refused_with_its_reason() -> None:
    """⚑ A non-literal flag, an unmodelled action, a lambda type: a worklist line, never a guess."""
    cases = {
        "parser.add_argument(FLAG)": "not a string literal",
        'parser.add_argument("--x", action="extend")': "not modelled",
        'parser.add_argument("--x", type=lambda s: s)': "type or nargs",
        'parser.add_argument("--x", nargs=ARITY)': "type or nargs",
    }
    for expression, why in cases.items():
        got = _field(expression)
        assert isinstance(got, str), (expression, got)
        assert why in got, (expression, got)


def test_a_parser_used_beyond_add_argument_and_parse_args_is_refused() -> None:
    """⚑ Subparsers, set_defaults and a parser handed on all reach the parser another way."""
    for extra in ("sub = parser.add_subparsers()", "parser.set_defaults(x=1)", "run(parser)"):
        src = _function(f'parser.add_argument("--x")\n{extra}\nargs = parser.parse_args()')
        got = typedargs.plan(src)
        assert got.text == src, extra
        assert got.parsers == 0, extra
        assert [r.function for r in got.refusals] == ["main"], extra
        assert "used beyond" in got.refusals[0].why, extra


def test_parser_error_calls_are_not_a_use_that_blocks_typing() -> None:
    """⚑ `parser.error(...)` exits and touches no field: nested in an `if`, it still types."""
    body = 'parser.add_argument("--x")\nargs = parser.parse_args()\n'
    got = typedargs.plan(_function(body + 'if not args.x:\n    parser.error("x")'))
    assert got.parsers == 1
    assert got.refusals == []
    assert "namespace=MainArgs()" in got.text


def test_a_mutually_exclusive_group_contributes_its_fields() -> None:
    """⚑ `mode.add_argument(...)` lands on the same namespace as the parser's own."""
    body = (
        "mode = parser.add_mutually_exclusive_group()\n"
        'mode.add_argument("--a", action="store_true")\n'
        'mode.add_argument("--b", type=int)\n'
        'parser.add_argument("--c", action="store_true")\n'
        "args = parser.parse_args()"
    )
    got = typedargs.plan(_function(body))
    assert got.parsers == 1
    assert got.refusals == []
    for field in ("a: bool", "b: int | None", "c: bool"):
        assert field in got.text, field


def test_a_group_used_beyond_add_argument_is_refused() -> None:
    """⚑ A group handed on, or given another method, reaches the namespace another way."""
    body = (
        "mode = parser.add_mutually_exclusive_group()\n"
        'mode.add_argument("--a", action="store_true")\n'
        "run(mode)\n"
        "args = parser.parse_args()"
    )
    got = typedargs.plan(_function(body))
    assert got.parsers == 0
    assert "group mode is used beyond add_argument" in got.refusals[0].why


def test_other_unfit_shapes_are_refused_with_their_reason() -> None:
    """⚑ Never parsed, two parsers, a shared destination: each names itself."""
    twice = 'parser.add_argument("--x")\nparser.add_argument("--x")\nargs = parser.parse_args()'
    cases = {
        'parser.add_argument("--x")': "never parsed",
        "other = argparse.ArgumentParser()": "more than one",
        twice: "share a destination",
    }
    for body, why in cases.items():
        src = _function(body)
        got = typedargs.plan(src)
        assert got.text == src, body
        assert len(got.refusals) == 1, (body, got.refusals)
        assert why in got.refusals[0].why, (body, got.refusals[0].why)


def test_a_module_that_cannot_take_the_class_is_refused() -> None:
    """⚑ No `from __future__ import annotations`, or the class name already taken."""
    body = 'parser.add_argument("--x")\nargs = parser.parse_args()'
    no_future = _function(body).replace("from __future__ import annotations\n\n", "")
    taken = _function(body).replace("\n\ndef main", "\n\nclass MainArgs:\n    pass\n\n\ndef main")
    for src, why in ((no_future, "lacks `from __future__"), (taken, "already defines")):
        got = typedargs.plan(src)
        assert got.text == src, why
        assert why in got.refusals[0].why, (why, got.refusals)


def test_running_it_again_is_a_no_op() -> None:
    """⚑ A parser that already has a namespace is not a refusal and not an edit."""
    again = typedargs.plan(TYPED)
    assert again.text == TYPED
    assert again.parsers == 0
    assert again.refusals == []


def test_a_file_without_a_parser_is_left_alone() -> None:
    """⚑ Nothing to do is not a refusal."""
    src = "def f() -> int:\n    return 1\n"
    got = typedargs.plan(src)
    assert got.text == src
    assert got.parsers == 0
    assert got.refusals == []


def test_a_file_that_does_not_parse_is_refused_whole() -> None:
    """⚑ A syntax error is reported at line 0 and the text is returned unchanged."""
    got = typedargs.plan("def f(:\n")
    assert got.text == "def f(:\n"
    assert got.refusals[0].line == 0
    assert "does not parse" in got.refusals[0].why


def test_the_class_goes_above_a_decorator() -> None:
    """⚑ The function's start is its first decorator, so the class never splits them."""
    src = SOURCE.replace("def main", "@decorate\ndef main")
    got = typedargs.plan(src)
    assert got.parsers == 1
    assert got.text.index("class MainArgs") < got.text.index("@decorate")


def test_a_cast_to_another_type_and_its_import_stay() -> None:
    """⚑ Only a cast equal to the declared type is dropped; `cast` stays imported for the rest."""
    src = SOURCE.replace('cast("Path | None", args.out)', 'cast("str", args.count)')
    got = typedargs.plan(src)
    assert 'cast("str", args.count)' in got.text
    assert "from typing import cast" in got.text
    assert got.parsers == 1


def test_two_functions_each_get_their_own_class() -> None:
    """⚑ Class names come from the function names and do not collide."""
    second = SOURCE.split("\n\n\n", 1)[1].replace("def main", "def other")
    src = SOURCE + "\n\n" + second
    got = typedargs.plan(src)
    assert got.parsers == TWO
    assert "class MainArgs" in got.text
    assert "class OtherArgs" in got.text
