# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2026 Mike Mol
"""W836: bazel admits or waits on the host's resources itself, before every heavy command.

A note told each session to read the zram fact before heavy bazel work, and a session that skipped
it filled zram1, which remounted /var/tmp read-only and killed every shell command (the 2026-10-05
outage). A rule that depends on being remembered is the manual step again (operator, 2026-10-06):
the check belongs in bazel's own path. Bazel runs a workspace's `tools/bazel` wrapper before every
client command, naming the real client in BAZEL_REAL; `mikemol-bazel-admit --install` writes that
wrapper, and the wrapper runs this.

⚑ ADMIT OR WAIT, NEVER GUESS. A light verb (`info`, `query`, `version`, `shutdown`, ...) runs at
once. A heavy verb (`build`, `test`, `run`, `coverage`, `fetch`) waits while zram is at or above
the refusal fraction (`host_facts.REFUSE_FRACTION`), saying so on stderr, and is REFUSED (exit 3)
after a bounded wait rather than run into the limit. Then it runs under a `mikemol-membudget` lease
for its estimated MB, which waits in turn while the host's other holders have spent the budget.

⚑ WHAT CANNOT BE READ BLOCKS NOTHING, AND SAYS SO: an unreadable zram admits with a note; a missing
`mikemol-membudget` runs bazel with a note. The gate guards the host from a known failure, and a
broken guard must not also stop all work. `BAZEL_ADMIT=0` bypasses it, stated on stderr.

⚑ THE WRAPPER FAILS OPEN WHEN THIS TOOL IS NOT BUILT: building this tool needs bazel, which would
need the wrapper, which needs the tool.

CONSUMED BY: the `mikemol-bazel-admit` console script.
"""

from __future__ import annotations

import os
import shutil
import sys
import time
from collections.abc import Callable, Sequence
from pathlib import Path
from typing import TYPE_CHECKING

from mikemol.hooks import host_facts, tool_path

if TYPE_CHECKING:
    from collections.abc import Mapping
    from typing import TextIO

HEAVY_MB = {"build": 4096, "test": 4096, "coverage": 4096, "run": 2048, "fetch": 1024}
MEMBUDGET = "mikemol-membudget"
MEMBUDGET_ENV = "MEMBUDGET_BIN"
LABEL = "bazel"
BYPASS_ENV = "BAZEL_ADMIT"
MAX_WAIT_ENV = "BAZEL_ADMIT_MAX_WAIT_S"
TRACE_ENV = "BAZEL_ADMIT_TRACE"
DEFAULT_MAX_WAIT_S = 3600.0
POLL_S = 10.0
SAY_EVERY_S = 60.0
EXIT_REFUSED = 3
EXIT_USAGE = 2
SEPARATOR = "--"
INSTALL_FLAG = "--install"
ARGC_WITH_VALUE = 2
WRAPPER_PATH = Path("tools") / "bazel"
WRAPPER = """#!/bin/sh
# Generated by `mikemol-bazel-admit --install` (mtools:W836). Bazel runs this before every client
# command, with the real client in BAZEL_REAL. Heavy commands (build, test, run, coverage, fetch)
# wait for host resources first; the rest run untouched. The tool is looked for in this repo's venv,
# then in mtools' built venv, then on PATH, and when it is not built (the bootstrap build needs
# this wrapper) bazel runs untouched.
here="$(cd "$(dirname "$0")/.." && pwd -P)"
for admit in \\
    "$here/.venv/bin/mikemol-bazel-admit" \\
    "$here/bazel-bin/hooks/.venv/bin/mikemol-bazel-admit"; do
    if [ -x "$admit" ]; then
        exec "$admit" -- "$BAZEL_REAL" "$@"
    fi
done
exec "$BAZEL_REAL" "$@"
"""

Reader = Callable[[], host_facts.Headroom | None]
Execute = Callable[[Sequence[str]], int]


def verb_of(args: Sequence[str]) -> str | None:
    """Name the bazel command in `args`: the first word that is not a startup option.

    Returns:
        the verb, or None when there is none (a bare `bazel`).

    """
    return next((word for word in args if not word.startswith("-")), None)


def estimate_mb(verb: str | None) -> int | None:
    """Estimate the memory a bazel command needs.

    Returns:
        the MB for a heavy verb, or None for a light one that needs no admission.

    """
    return HEAVY_MB.get(verb) if verb is not None else None


def wait_for_zram(
    read: Reader,
    sleep: Callable[[float], None],
    clock: Callable[[], float],
    say: Callable[[str], None],
    max_wait_s: float,
) -> bool:
    """Wait until zram is below the refusal fraction, or the wait is spent.

    Returns:
        True to admit (headroom, or zram unreadable), False when it stayed full too long.

    """
    started = clock()
    last_said = started - SAY_EVERY_S
    while True:
        headroom = read()
        if headroom is None:
            say("bazel-admit: zram is unreadable; admitting without its headroom check")
            return True
        fraction = headroom.fraction()
        if fraction < host_facts.REFUSE_FRACTION:
            return True
        now = clock()
        if now - started >= max_wait_s:
            return False
        if now - last_said >= SAY_EVERY_S:
            left = max_wait_s - (now - started)
            say(
                f"bazel-admit: waiting for zram headroom ({fraction:.0%} of its limit; admits "
                f"below {host_facts.REFUSE_FRACTION:.0%}); giving up in {left:.0f}s"
            )
            last_said = now
        sleep(POLL_S)


def plan(
    real: str, args: Sequence[str], mb: int, env: Mapping[str, str], root: Path
) -> tuple[list[str], str | None]:
    """Build the command to run for an admitted heavy verb, under a lease when one is available.

    Returns:
        the argv, and a note to say when the lease could not be taken.

    """
    budget = tool_path.find(MEMBUDGET, MEMBUDGET_ENV, root, env)
    if budget is None:
        return [real, *args], f"bazel-admit: {MEMBUDGET} not found; running without a memory lease"
    # ⚑ `hold`, NOT `run`: `run` caps the command's cgroup at its lease, and the bazel client that
    # starts the server daemon would put the daemon, which outlives the command and does the real
    # work, inside that cap for good (measured: `run 4096` printed MemoryMax=4096M). `hold` admits
    # against the same ledger and releases when the client exits, with no cap.
    return [str(budget), "hold", str(mb), LABEL, SEPARATOR, real, *args], None


def admit(
    argv: Sequence[str],
    env: Mapping[str, str],
    execute: Execute,
    err: TextIO,
    read: Reader = host_facts.zram_headroom,
) -> int:
    """Run `argv` (the real bazel and its arguments) after admitting it.

    Returns:
        what `execute` returns for the command that ran, or EXIT_REFUSED when zram stayed full.

    """
    real, args = argv[0], list(argv[1:])
    verb = verb_of(args)
    mb = estimate_mb(verb)
    if env.get(BYPASS_ENV) == "0":
        err.write("bazel-admit: BAZEL_ADMIT=0, running without admission\n")
        return execute([real, *args])
    if mb is None:
        if env.get(TRACE_ENV):
            err.write(f"bazel-admit: `{verb}` is light; running untouched\n")
        return execute([real, *args])
    limit = float(env.get(MAX_WAIT_ENV) or DEFAULT_MAX_WAIT_S)

    def say(text: str) -> None:
        err.write(f"{text}\n")

    if not wait_for_zram(read, time.sleep, time.monotonic, say, limit):
        err.write(
            f"bazel-admit: zram stayed above {host_facts.REFUSE_FRACTION:.0%} for {limit:.0f}s; "
            f"`bazel {verb}` refused ({BYPASS_ENV}=0 overrides)\n"
        )
        return EXIT_REFUSED
    command, note = plan(real, args, mb, env, Path.cwd())
    if note:
        err.write(f"{note}\n")
    if env.get(TRACE_ENV):
        err.write(f"bazel-admit: admitted `{verb}` ({mb} MB): {' '.join(command)}\n")
    return execute(command)


def install(repo: Path) -> Path:
    """Write the repository's `tools/bazel` wrapper.

    Returns:
        the wrapper's path, executable.

    """
    target = repo / WRAPPER_PATH
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(WRAPPER, encoding="utf-8")
    target.chmod(0o755)
    return target


def _exec(argv: Sequence[str]) -> int:
    """Replace this process with `argv`; it does not return unless the program is missing.

    Returns:
        127 when the program could not be started.

    """
    program = shutil.which(argv[0]) or argv[0]
    try:
        os.execv(program, list(argv))
    except OSError as problem:
        sys.stderr.write(f"bazel-admit: cannot run {argv[0]}: {problem}\n")
        return 127


def main(argv: Sequence[str] | None = None) -> int:
    """Run `mikemol-bazel-admit -- <real bazel> <args>`, or `--install DIR`.

    Returns:
        the command's exit code, EXIT_REFUSED, or EXIT_USAGE.

    """
    args = list(sys.argv[1:] if argv is None else argv)
    if len(args) == ARGC_WITH_VALUE and args[0] == INSTALL_FLAG:
        sys.stdout.write(f"{install(Path(args[1]))}\n")
        return 0
    if len(args) >= ARGC_WITH_VALUE and args[0] == SEPARATOR:
        return admit(args[1:], dict(os.environ), _exec, sys.stderr)
    sys.stderr.write("usage: mikemol-bazel-admit -- <bazel> [args...] | --install DIR\n")
    return EXIT_USAGE
