# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2026 Mike Mol
"""Own the engine's generated DAG file: render it, write it, and check it fresh.

The derivation lives in `dagderive`, and the question of which modules the partition names lives
in `dagnames`. This module owns the artifact: its header, its rendering, and the write and check
contract that the engine's regeneration gate invokes.

An edge's value is a module path, not a bare stem. Both sides of an edge name the namespace a
build target uses, so the build resolves a dependency by stripping the suffix and needs no
translation from stems. This is the current writer; `imports` is the legacy one and records stems,
so running both on one file flips it between the two formats.

The header is emitted from here, and it cites rather than restates. A render that copied whatever
preceded the dict would carry hand-maintained prose through every regeneration, authored by nobody
the generator knew about and compared to nothing: accurate by luck, one design change from being a
retired premise stamped into a fresh artifact. A derived artifact carrying a retired premise is
worse than stale prose because it looks like data, so the rule is to cite the authority and never
restate it.

The file is written with the sibling distribution's atomic write: a torn write of the DAG file
would leave the build graph half stated.

    python3 -m mikemol.importdag.dagbzl [--engine DIR] --check     # byte-compare, gated
    python3 -m mikemol.importdag.dagbzl [--engine DIR] --write     # regenerate
"""

from __future__ import annotations

import sys

from mikemol.atomicwrite.durable import write_atomic

from mikemol.importdag import dagderive, dagnames

HEADER = """# GENERATED by mikemol.importdag.dagbzl - do not edit, and do not add prose here: this
# whole file is rewritten, header included, so anything written by hand is lost or (worse)
# preserved past the point it stays true. What this file IS, and why, is documented at the owner:
#   mikemol.importdag.dagderive   how the edges are derived (AST, never grep)
#   mikemol.importdag.dagbzl      how this artifact is rendered and gated
#   paperkit/components.bzl       the module partition the edges are derived over
# REGENERATE: python3 -m mikemol.importdag.dagbzl --write   |   VERIFY: --check (byte-compare)
"""
"""The generated file's header, with the authorities it cites."""


def render_with(header: str, rows: list[tuple[str, str]]) -> str:
    """Render a DAG file under `header`, one line per importing module.

    The body is shared with the legacy writer, which differs only in its header and in what an
    edge's value is.

    Returns:
        The header followed by the `IMPORTS` dict, modules sorted, each value list sorted.

    """
    by_mod: dict[str, set[str]] = {}
    for m, i in rows:
        by_mod.setdefault(m, set()).add(i)
    body = "".join(
        '    "{}": [{}],\n'.format(m, ", ".join(f'"{x}"' for x in sorted(v)))
        for m, v in sorted(by_mod.items())
    )
    return header + "IMPORTS = {\n" + body + "}\n"


def render(rows: list[tuple[str, str]]) -> str:
    """Render the DAG file in full, header included, so nothing hand-written survives.

    Returns:
        The header followed by the `IMPORTS` dict, each side of an edge a module path.

    """
    return render_with(HEADER, rows)


def main(argv: list[str] | None = None) -> int:
    """Write or check `dag.bzl` of the engine against a fresh derivation.

    The mode is the first word after any `--engine DIR`, and defaults to `--check`.

    Returns:
        0 when the file is fresh or was regenerated, 1 when `--check` finds it stale, and 2 for a
        mode that is neither.

    """
    eng, rest = dagnames.split_engine(sys.argv[1:] if argv is None else argv)
    dag = eng / "dag.bzl"
    want = render(dagderive.edges(eng, dagnames.engine_srcs(eng)))
    mode = rest[0] if rest else "--check"

    if mode == "--check":
        if dag.read_text(encoding="utf-8") != want:
            sys.stderr.write(
                f"dagbzl --check: {eng.name}/dag.bzl is STALE - regenerate with "
                "`python3 -m mikemol.importdag.dagbzl --write`\n"
            )
            return 1
        sys.stdout.write("dagbzl --check: dag.bzl is fresh\n")
        return 0

    if mode == "--write":
        if dag.read_text(encoding="utf-8") == want:
            sys.stdout.write("dagbzl --write: dag.bzl already fresh\n")
            return 0
        write_atomic(dag, want)
        sys.stdout.write(f"dagbzl --write: regenerated {eng.name}/dag.bzl\n")
        return 0

    sys.stderr.write(f"dagbzl: unknown mode {mode!r} - expected --check or --write\n")
    return 2


if __name__ == "__main__":
    raise SystemExit(main())
