# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2026 Mike Mol
"""Enumerate an engine's internal import edges, and own the legacy stem-valued DAG file.

An edge is a module and another module of the given set that it imports flat, read from the syntax
tree and never by text search: a text search matches the name in comments and strings, and the
"cycle" once reported between two projects was such a phantom. The build graph is a projection of
these edges, because each module's bytecode is a target whose dependencies are its imports, so a
consumer stages a module's transitive closure rather than the flat engine.

This is the LEGACY writer. It records an edge as a path-shaped key against a bare-stem value, which
is the format `dagbzl` replaced with path-valued edges. Running `--write` here and `--write` there
flips the file between the two formats, so one of them must be the only writer of a given file; see
`dagbzl` for the one that is current.

    python3 -m mikemol.importdag.imports [--engine DIR] MODULE.py ...    # the edges over a set
    python3 -m mikemol.importdag.imports [--engine DIR] --write          # regenerate dag.bzl
    python3 -m mikemol.importdag.imports [--engine DIR] --check          # byte-compare, gated

The file is written with the sibling distribution's atomic write, so a crash cannot leave the build
graph half stated.
"""

from __future__ import annotations

import sys
from pathlib import Path

from mikemol.atomicwrite.durable import write_atomic

from mikemol.importdag import dagnames
from mikemol.importdag.dagbzl import render_with
from mikemol.importdag.dagderive import flat_imports

HEADER = """# GENERATED by mikemol.importdag.imports - do not edit, and do not add prose here: this
# whole file is rewritten, header included, so anything written by hand is lost or (worse)
# preserved past the point it stays true. What this file IS, and why, is documented at the owner:
#   mikemol.importdag.imports   how the edges are derived (AST, never grep)
#   paperkit/components.bzl     the module partition the edges are derived over
# REGENERATE: python3 -m mikemol.importdag.imports --write   |   VERIFY: --check (byte-compare)
"""
"""The generated file's header, owned by the generator, which cites the authority and does not
restate it, so no hand-maintained prose survives a regeneration."""

MODES = ("--write", "--check")


def edges(eng: Path, paths: list[str]) -> list[tuple[str, str]]:
    """Return every engine-internal import edge as importer path and imported stem.

    Returns:
        The edges in `paths` order, each importer's imports sorted by stem. A module's import of
        its own stem is not an edge.

    """
    names = {Path(p).stem for p in paths}
    out: list[tuple[str, str]] = []
    for p in paths:
        stem = Path(p).stem
        found = flat_imports((eng / p).read_text(encoding="utf-8"), names) - {stem}
        out.extend((p, imp) for imp in sorted(found))
    return out


def render(rows: list[tuple[str, str]]) -> str:
    """Render the DAG file in full, header included, so nothing hand-written survives.

    Returns:
        The header followed by the `IMPORTS` dict, one line per importing module.

    """
    return render_with(HEADER, rows)


def run_mode(eng: Path, mode: str) -> int:
    """Write or check `eng/dag.bzl` against a fresh derivation.

    The check is the same computation as the write, asserting instead of writing, so the gate runs
    the writer's own code path and cannot drift from it.

    Returns:
        0 when the file is fresh or was regenerated, 1 when `--check` finds it stale.

    """
    want = render(edges(eng, dagnames.engine_srcs(eng)))
    dag = eng / "dag.bzl"
    if mode == "--check":
        if dag.read_text(encoding="utf-8") != want:
            sys.stderr.write(
                f"imports --check: {eng.name}/dag.bzl is STALE - regenerate with "
                "`python3 -m mikemol.importdag.imports --write`\n"
            )
            return 1
        sys.stdout.write("imports --check: dag.bzl is fresh\n")
        return 0
    if dag.read_text(encoding="utf-8") == want:
        sys.stdout.write("imports --write: dag.bzl already fresh\n")
        return 0
    write_atomic(dag, want)
    sys.stdout.write(f"imports --write: regenerated {eng.name}/dag.bzl\n")
    return 0


def main(argv: list[str] | None = None) -> int:
    """Print the edges over the named modules, or write or check the engine's DAG file.

    Returns:
        The exit code of the mode when `--write` or `--check` leads, else 0 after printing one
        `importer`, tab, `imported` line per edge.

    """
    eng, rest = dagnames.split_engine(sys.argv[1:] if argv is None else argv)
    if rest and rest[0] in MODES:
        return run_mode(eng, rest[0])
    for p, imp in edges(Path(), rest):
        sys.stdout.write(f"{p}\t{imp}\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
