# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2026 Mike Mol
"""Witnesses for `imports`: the legacy stem-valued DAG file, and that it is written atomically."""

from __future__ import annotations

import os
import subprocess
import sys
from typing import TYPE_CHECKING

from mikemol.importdag import dagbzl
from mikemol.importdag.imports import HEADER, MODES, edges, main, render, run_mode

if TYPE_CHECKING:
    from pathlib import Path

    import pytest

MODE = 0o640

COMPONENTS = """\
COMPONENTS = {
    "core": ["a.py", "b.py"],
    "more": ["tools/c.py"],
}
"""

STEM_BODY = 'IMPORTS = {\n    "a.py": ["b", "c"],\n    "tools/c.py": ["b"],\n}\n'


def _engine(tmp_path: Path) -> Path:
    """Build an engine whose `a` imports `b` and `c`, and whose `c` imports `b`.

    Returns:
        The engine directory, named `eng`.

    """
    eng = tmp_path / "eng"
    (eng / "tools").mkdir(parents=True)
    (eng / "components.bzl").write_text(COMPONENTS, encoding="utf-8")
    (eng / "a.py").write_text("import b\nfrom eng import c\nimport c\nimport a\n", "utf-8")
    (eng / "b.py").write_text("VALUE = 1\n", encoding="utf-8")
    (eng / "tools" / "c.py").write_text("import b\n", encoding="utf-8")
    return eng


def test_edges_are_importer_path_and_imported_stem(tmp_path: Path) -> None:
    """The value is a bare stem, a self-import is no edge, and edges follow the path order."""
    eng = _engine(tmp_path)
    got = edges(eng, ["a.py", "b.py", "tools/c.py"])
    assert got == [("a.py", "b"), ("a.py", "c"), ("tools/c.py", "b")]


def test_render_is_the_header_then_the_stem_valued_dict() -> None:
    """The file is the header and the dict; a repeated edge is written once."""
    rows = [("a.py", "c"), ("a.py", "b"), ("a.py", "b"), ("tools/c.py", "b")]
    assert render(rows) == HEADER + STEM_BODY


def test_header_cites_this_module_and_not_the_paperkit_script() -> None:
    """The generated header names the module that now owns the file, and says it is generated."""
    assert HEADER.startswith("# GENERATED by mikemol.importdag.imports - do not edit")
    assert "tools/imports.py" not in HEADER
    assert "python3 -m mikemol.importdag.imports --write" in HEADER


def test_run_mode_check_passes_a_fresh_file(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    """A byte-equal file passes with exit 0."""
    eng = _engine(tmp_path)
    (eng / "dag.bzl").write_text(HEADER + STEM_BODY, encoding="utf-8")
    assert run_mode(eng, "--check") == 0
    assert capsys.readouterr().out == "imports --check: dag.bzl is fresh\n"


def test_run_mode_check_fails_a_stale_file(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    """A different file fails with exit 1 and a message naming the repair."""
    eng = _engine(tmp_path)
    (eng / "dag.bzl").write_text("IMPORTS = {}\n", encoding="utf-8")
    assert run_mode(eng, "--check") == 1
    err = capsys.readouterr().err
    assert err == (
        "imports --check: eng/dag.bzl is STALE - regenerate with "
        "`python3 -m mikemol.importdag.imports --write`\n"
    )


def test_run_mode_write_regenerates_then_is_idempotent(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    """The first write replaces the file, the second finds it fresh and leaves it."""
    eng = _engine(tmp_path)
    (eng / "dag.bzl").write_text("old\n", encoding="utf-8")
    assert run_mode(eng, "--write") == 0
    assert (eng / "dag.bzl").read_text(encoding="utf-8") == HEADER + STEM_BODY
    assert capsys.readouterr().out == "imports --write: regenerated eng/dag.bzl\n"
    assert run_mode(eng, "--write") == 0
    assert capsys.readouterr().out == "imports --write: dag.bzl already fresh\n"


def test_write_is_atomic_so_a_hardlinked_twin_keeps_its_bytes(tmp_path: Path) -> None:
    """The sibling's atomic write replaces the path: a twin of the old inode is not rewritten."""
    eng = _engine(tmp_path)
    (eng / "dag.bzl").write_text("old\n", encoding="utf-8")
    twin = tmp_path / "twin.bzl"
    os.link(eng / "dag.bzl", twin)
    assert run_mode(eng, "--write") == 0
    assert (eng / "dag.bzl").read_text(encoding="utf-8") == HEADER + STEM_BODY
    assert twin.read_text(encoding="utf-8") == "old\n"


def test_write_preserves_the_files_permissions(tmp_path: Path) -> None:
    """The replace keeps the mode the file had, as the sibling's write promises."""
    eng = _engine(tmp_path)
    dag = eng / "dag.bzl"
    dag.write_text("old\n", encoding="utf-8")
    dag.chmod(MODE)
    assert run_mode(eng, "--write") == 0
    assert dag.stat().st_mode & 0o777 == MODE


def test_main_lists_edges_over_the_named_modules(
    tmp_path: Path, capsys: pytest.CaptureFixture[str], monkeypatch: pytest.MonkeyPatch
) -> None:
    """Without a mode word, the edges over the given files are printed tab separated."""
    eng = _engine(tmp_path)
    monkeypatch.chdir(eng)
    assert main(["a.py", "b.py", "tools/c.py"]) == 0
    assert capsys.readouterr().out == "a.py\tb\na.py\tc\ntools/c.py\tb\n"


def test_main_takes_the_engine_option_for_a_mode(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    """`--engine DIR` locates the engine, with the mode after it."""
    eng = _engine(tmp_path)
    (eng / "dag.bzl").write_text("old\n", encoding="utf-8")
    assert main(["--engine", str(eng), "--write"]) == 0
    assert (eng / "dag.bzl").read_text(encoding="utf-8") == HEADER + STEM_BODY
    assert capsys.readouterr().out == "imports --write: regenerated eng/dag.bzl\n"


def test_main_defaults_the_engine_to_paperkit_under_the_working_directory(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch, capsys: pytest.CaptureFixture[str]
) -> None:
    """With no option the engine directory is `paperkit` under the cwd."""
    eng = _engine(tmp_path)
    eng.rename(tmp_path / "paperkit")
    (tmp_path / "paperkit" / "dag.bzl").write_text(HEADER + STEM_BODY, encoding="utf-8")
    monkeypatch.chdir(tmp_path)
    monkeypatch.setattr(sys, "argv", ["imports", "--check"])
    assert main() == 0
    assert capsys.readouterr().out == "imports --check: dag.bzl is fresh\n"


def test_modes_are_write_and_check() -> None:
    """The two mode words the command line recognises."""
    assert MODES == ("--write", "--check")


def test_the_two_writers_disagree_on_the_same_file(tmp_path: Path) -> None:
    """Running the legacy writer and the current one flips the file between two formats."""
    eng = _engine(tmp_path)
    (eng / "dag.bzl").write_text("old\n", encoding="utf-8")
    assert run_mode(eng, "--write") == 0
    legacy = (eng / "dag.bzl").read_text(encoding="utf-8")
    assert dagbzl.main(["--engine", str(eng), "--check"]) == 1
    assert dagbzl.main(["--engine", str(eng), "--write"]) == 0
    assert (eng / "dag.bzl").read_text(encoding="utf-8") != legacy
    assert run_mode(eng, "--check") == 1


def test_runs_as_a_module(tmp_path: Path) -> None:
    """`python -m mikemol.importdag.imports` exits with `main`'s code."""
    eng = _engine(tmp_path)
    (eng / "dag.bzl").write_text("old\n", encoding="utf-8")
    r = subprocess.run(
        [sys.executable, "-m", "mikemol.importdag.imports", "--engine", str(eng), "--check"],
        cwd=tmp_path,
        capture_output=True,
        text=True,
        check=False,
    )
    assert r.returncode == 1
    assert "STALE" in r.stderr
