# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2026 Mike Mol
"""Witnesses for `dagbzl`: the path-valued DAG file, its modes, and its atomic write."""

from __future__ import annotations

import os
import subprocess
import sys
from typing import TYPE_CHECKING

from mikemol.importdag.dagbzl import HEADER, main, render, render_with

if TYPE_CHECKING:
    from pathlib import Path

    import pytest

MODE = 0o640
USAGE_ERROR = 2

COMPONENTS = """\
COMPONENTS = {
    "core": ["a.py", "b.py"],
    "more": ["tools/c.py"],
}
"""

BODY = 'IMPORTS = {\n    "a.py": ["b.py", "tools/c.py"],\n    "tools/c.py": ["b.py"],\n}\n'


def _engine(tmp_path: Path) -> Path:
    """Build an engine whose `a` imports `b` and `c`, and whose `c` imports `b`.

    Returns:
        The engine directory, named `eng`.

    """
    eng = tmp_path / "eng"
    (eng / "tools").mkdir(parents=True)
    (eng / "components.bzl").write_text(COMPONENTS, encoding="utf-8")
    (eng / "a.py").write_text("import b\nimport c\nimport a\n", encoding="utf-8")
    (eng / "b.py").write_text("VALUE = 1\n", encoding="utf-8")
    (eng / "tools" / "c.py").write_text("import b\n", encoding="utf-8")
    return eng


def test_render_with_sorts_and_deduplicates_under_the_given_header() -> None:
    """Modules and values are sorted, a repeated edge is written once, the header leads."""
    rows = [("z.py", "a.py"), ("m.py", "y.py"), ("m.py", "b.py"), ("m.py", "b.py")]
    want = 'H\nIMPORTS = {\n    "m.py": ["b.py", "y.py"],\n    "z.py": ["a.py"],\n}\n'
    assert render_with("H\n", rows) == want


def test_render_values_are_module_paths_under_the_dagbzl_header() -> None:
    """The current format: a path on both sides of an edge, after this module's header."""
    rows = [("a.py", "tools/c.py"), ("a.py", "b.py"), ("tools/c.py", "b.py")]
    assert render(rows) == HEADER + BODY


def test_header_cites_this_module_and_not_the_paperkit_script() -> None:
    """The header names the modules that own the file and how to regenerate it."""
    assert HEADER.startswith("# GENERATED by mikemol.importdag.dagbzl - do not edit")
    assert "tools/dagbzl.py" not in HEADER
    assert "#   mikemol.importdag.dagderive   how the edges are derived" in HEADER
    assert "python3 -m mikemol.importdag.dagbzl --write" in HEADER


def test_check_passes_a_fresh_file_and_is_the_default_mode(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    """A byte-equal file passes; naming no mode means `--check`."""
    eng = _engine(tmp_path)
    (eng / "dag.bzl").write_text(HEADER + BODY, encoding="utf-8")
    assert main(["--engine", str(eng)]) == 0
    assert capsys.readouterr().out == "dagbzl --check: dag.bzl is fresh\n"


def test_check_fails_a_stale_file(tmp_path: Path, capsys: pytest.CaptureFixture[str]) -> None:
    """A different file fails with exit 1 and a message naming the repair."""
    eng = _engine(tmp_path)
    (eng / "dag.bzl").write_text("IMPORTS = {}\n", encoding="utf-8")
    assert main(["--engine", str(eng), "--check"]) == 1
    assert capsys.readouterr().err == (
        "dagbzl --check: eng/dag.bzl is STALE - regenerate with "
        "`python3 -m mikemol.importdag.dagbzl --write`\n"
    )


def test_write_regenerates_then_is_idempotent(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    """The first write replaces the file, the second finds it fresh."""
    eng = _engine(tmp_path)
    (eng / "dag.bzl").write_text("old\n", encoding="utf-8")
    assert main(["--engine", str(eng), "--write"]) == 0
    assert (eng / "dag.bzl").read_text(encoding="utf-8") == HEADER + BODY
    assert capsys.readouterr().out == "dagbzl --write: regenerated eng/dag.bzl\n"
    assert main(["--engine", str(eng), "--write"]) == 0
    assert capsys.readouterr().out == "dagbzl --write: dag.bzl already fresh\n"


def test_write_is_atomic_so_a_hardlinked_twin_keeps_its_bytes(tmp_path: Path) -> None:
    """The sibling's atomic write replaces the path: a twin of the old inode is not rewritten."""
    eng = _engine(tmp_path)
    (eng / "dag.bzl").write_text("old\n", encoding="utf-8")
    twin = tmp_path / "twin.bzl"
    os.link(eng / "dag.bzl", twin)
    assert main(["--engine", str(eng), "--write"]) == 0
    assert (eng / "dag.bzl").read_text(encoding="utf-8") == HEADER + BODY
    assert twin.read_text(encoding="utf-8") == "old\n"


def test_write_preserves_the_files_permissions(tmp_path: Path) -> None:
    """The replace keeps the mode the file had, as the sibling's write promises."""
    eng = _engine(tmp_path)
    dag = eng / "dag.bzl"
    dag.write_text("old\n", encoding="utf-8")
    dag.chmod(MODE)
    assert main(["--engine", str(eng), "--write"]) == 0
    assert dag.stat().st_mode & 0o777 == MODE


def test_an_unknown_mode_is_refused_with_exit_2(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    """Neither mode word: exit 2 and a message naming it, with the file untouched."""
    eng = _engine(tmp_path)
    (eng / "dag.bzl").write_text("old\n", encoding="utf-8")
    assert main(["--engine", str(eng), "--bogus"]) == USAGE_ERROR
    err = capsys.readouterr().err
    assert err == "dagbzl: unknown mode '--bogus' - expected --check or --write\n"
    assert (eng / "dag.bzl").read_text(encoding="utf-8") == "old\n"


def test_the_engine_defaults_to_paperkit_under_the_working_directory(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch, capsys: pytest.CaptureFixture[str]
) -> None:
    """With no option the engine is `paperkit` under the cwd, and argv comes from the process."""
    _engine(tmp_path).rename(tmp_path / "paperkit")
    (tmp_path / "paperkit" / "dag.bzl").write_text(HEADER + BODY, encoding="utf-8")
    monkeypatch.chdir(tmp_path)
    monkeypatch.setattr(sys, "argv", ["dagbzl", "--check"])
    assert main() == 0
    assert capsys.readouterr().out == "dagbzl --check: dag.bzl is fresh\n"


def test_runs_as_a_module(tmp_path: Path) -> None:
    """`python -m mikemol.importdag.dagbzl` exits with `main`'s code."""
    eng = _engine(tmp_path)
    (eng / "dag.bzl").write_text("old\n", encoding="utf-8")
    r = subprocess.run(
        [sys.executable, "-m", "mikemol.importdag.dagbzl", "--engine", str(eng), "--write"],
        cwd=tmp_path,
        capture_output=True,
        text=True,
        check=False,
    )
    assert r.returncode == 0
    assert (eng / "dag.bzl").read_text(encoding="utf-8") == HEADER + BODY
